name: 'ethiopianmedicaldatawarehouse'
version: '1.0'
config-version: 2
profile: 'default'

models:
  ethiopianmedicaldatawarehouse:
    raw_data:
      materialized: view
    medical_data:
      materialized: table
