name: Python application

on:
  push:
    branches:  "task-4" 
  pull_request:
    branches:  "main" 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn sqlalchemy psycopg2-binary pydantic pytest

    - name: Run tests
      run: pytest
